// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { Database } from "@/types/database";
import { env } from "@/lib/config";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseUrl = env.VITE_PROJECT_URL;
const supabaseAnonKey = env.VITE_SECRET_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Missing Supabase environment variables");
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  db: {
    schema: "public",
  },
});
